[package]
name = "rust-wasm-projection"
version = "0.1.0"
edition = "2024"

[dependencies]
grap-f64 = { path = "../../grap/libraries/grap-f64" }
progred-graph = { path = "../../graph/progred-graph" }
serde_json = "1.0"
wasmtime = { version = "47.0.2", default-features = false, features = ["cranelift", "runtime", "wat", "std", "parallel-compilation"] }

[dev-dependencies]
progred-text = { path = "../../graph/conventions/progred-text" }
