import { bindMaybe, mapMaybe, Maybe } from "../lib/Maybe"
import type { D } from "./render/D"
import * as G from "./graph"
import { descend, Render } from "./render/R"
import { renderOtherFields } from "./render/renderOtherFields"

export function renderIfAlgebraicType(f: (_name: D, _ctorOrAlgebraicTypes: D, __algebraicType: G.AlgebraicType) => Maybe<D>, rs: {name?: Render, ctorOrAlgebraicTypes?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.AlgebraicType.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), descend(cursor, x.id, G.ctorOrAlgebraicTypesField.id, rs.ctorOrAlgebraicTypes, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField,G.ctorOrAlgebraicTypesField], cyclePath))) }
export function renderIfAnd(f: (__and: G.And) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.And.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfApp(f: (_name: D, __app: G.App) => Maybe<D>, rs: {name?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.App.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField], cyclePath))) }
export function renderIfAppPlatform(f: (_app: D, _platform: D, __appPlatform: G.AppPlatform) => Maybe<D>, rs: {app?: Render, platform?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.AppPlatform.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.appField.id, rs.app, undefined, cyclePath), descend(cursor, x.id, G.platformField.id, rs.platform, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.appField,G.platformField], cyclePath))) }
export function renderIfArrayLiteral(f: (_expressions: D, __arrayLiteral: G.ArrayLiteral) => Maybe<D>, rs: {expressions?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.ArrayLiteral.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.expressionsField.id, rs.expressions, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.expressionsField], cyclePath))) }
export function renderIfArrowFunction(f: (_parameters: D, _statements: D, __arrowFunction: G.ArrowFunction) => Maybe<D>, rs: {parameters?: Render, statements?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.ArrowFunction.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.parametersField.id, rs.parameters, undefined, cyclePath), descend(cursor, x.id, G.statementsField.id, rs.statements, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.parametersField,G.statementsField], cyclePath))) }
export function renderIfAssignment(f: (__assignment: G.Assignment) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Assignment.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfAtomicType(f: (_name: D, __atomicType: G.AtomicType) => Maybe<D>, rs: {name?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.AtomicType.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField], cyclePath))) }
export function renderIfBinaryInline(f: (_left: D, _binaryOperator: D, _right: D, __binaryInline: G.BinaryInline) => Maybe<D>, rs: {left?: Render, binaryOperator?: Render, right?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.BinaryInline.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.leftField.id, rs.left, undefined, cyclePath), descend(cursor, x.id, G.binaryOperatorField.id, rs.binaryOperator, undefined, cyclePath), descend(cursor, x.id, G.rightField.id, rs.right, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.leftField,G.binaryOperatorField,G.rightField], cyclePath))) }
export function renderIfBlock(f: (_children: D, __block: G.Block) => Maybe<D>, rs: {children?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Block.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.childrenField.id, rs.children, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.childrenField], cyclePath))) }
export function renderIfBradParams(f: (_adProbability: D, _minimumCheckpointsPerAd: D, _timeIntervalPerAd: D, _fetchPeriod: D, _tiers: D, __bradParams: G.BradParams) => Maybe<D>, rs: {adProbability?: Render, minimumCheckpointsPerAd?: Render, timeIntervalPerAd?: Render, fetchPeriod?: Render, tiers?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.BradParams.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.adProbabilityField.id, rs.adProbability, undefined, cyclePath), descend(cursor, x.id, G.minimumCheckpointsPerAdField.id, rs.minimumCheckpointsPerAd, undefined, cyclePath), descend(cursor, x.id, G.timeIntervalPerAdField.id, rs.timeIntervalPerAd, undefined, cyclePath), descend(cursor, x.id, G.fetchPeriodField.id, rs.fetchPeriod, undefined, cyclePath), descend(cursor, x.id, G.tiersField.id, rs.tiers, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.adProbabilityField,G.minimumCheckpointsPerAdField,G.timeIntervalPerAdField,G.fetchPeriodField,G.tiersField], cyclePath))) }
export function renderIfConditional(f: (_condition: D, _trueExpression: D, _falseExpression: D, __conditional: G.Conditional) => Maybe<D>, rs: {condition?: Render, trueExpression?: Render, falseExpression?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Conditional.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.conditionField.id, rs.condition, undefined, cyclePath), descend(cursor, x.id, G.trueExpressionField.id, rs.trueExpression, undefined, cyclePath), descend(cursor, x.id, G.falseExpressionField.id, rs.falseExpression, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.conditionField,G.trueExpressionField,G.falseExpressionField], cyclePath))) }
export function renderIfConst(f: (__const: G.Const) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Const.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfCtor(f: (_name: D, _fields: D, __ctor: G.Ctor) => Maybe<D>, rs: {name?: Render, fields?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Ctor.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), descend(cursor, x.id, G.fieldsField.id, rs.fields, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField,G.fieldsField], cyclePath))) }
export function renderIfCtorField(f: (_ctor: D, __ctorField: G.CtorField) => Maybe<D>, rs: {ctor?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.CtorField.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.ctorField.id, rs.ctor, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.ctorField], cyclePath))) }
export function renderIfDescend(f: (_field: D, _contextRender: D, __descend: G.Descend) => Maybe<D>, rs: {field?: Render, contextRender?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Descend.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.fieldField.id, rs.field, undefined, cyclePath), descend(cursor, x.id, G.contextRenderField.id, rs.contextRender, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.fieldField,G.contextRenderField], cyclePath))) }
export function renderIfDifference(f: (__difference: G.Difference) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Difference.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfDispatch(f: (_renders: D, __dispatch: G.Dispatch) => Maybe<D>, rs: {renders?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Dispatch.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.rendersField.id, rs.renders, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.rendersField], cyclePath))) }
export function renderIfDot(f: (__dot: G.Dot) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Dot.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfEmptyList(f: (__emptyList: G.EmptyList) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.EmptyList.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfEquals(f: (__equals: G.Equals) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Equals.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfEvaluate(f: (_javascriptProgram: D, __evaluate: G.Evaluate) => Maybe<D>, rs: {javascriptProgram?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Evaluate.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.javascriptProgramField.id, rs.javascriptProgram, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.javascriptProgramField], cyclePath))) }
export function renderIfExtern(f: (_name: D, __extern: G.Extern) => Maybe<D>, rs: {name?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Extern.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField], cyclePath))) }
export function renderIfField(f: (_name: D, _type: D, __field: G.Field) => Maybe<D>, rs: {name?: Render, type?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Field.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), descend(cursor, x.id, G.typeField.id, rs.type, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField,G.typeField], cyclePath))) }
export function renderIfFunctionCall(f: (_function: D, _arguments: D, __functionCall: G.FunctionCall) => Maybe<D>, rs: {function?: Render, arguments?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.FunctionCall.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.functionField.id, rs.function, undefined, cyclePath), descend(cursor, x.id, G.argumentsField.id, rs.arguments, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.functionField,G.argumentsField], cyclePath))) }
export function renderIfFunctionDeclaration(f: (_name: D, _parameters: D, _statements: D, __functionDeclaration: G.FunctionDeclaration) => Maybe<D>, rs: {name?: Render, parameters?: Render, statements?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.FunctionDeclaration.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), descend(cursor, x.id, G.parametersField.id, rs.parameters, undefined, cyclePath), descend(cursor, x.id, G.statementsField.id, rs.statements, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField,G.parametersField,G.statementsField], cyclePath))) }
export function renderIfGreaterThan(f: (__greaterThan: G.GreaterThan) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.GreaterThan.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfGreaterThanOrEqualTo(f: (__greaterThanOrEqualTo: G.GreaterThanOrEqualTo) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.GreaterThanOrEqualTo.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfHouseAdEntry(f: (_weight: D, _lifetimeCap: D, _name: D, _actionURL: D, _images: D, __houseAdEntry: G.HouseAdEntry) => Maybe<D>, rs: {weight?: Render, lifetimeCap?: Render, name?: Render, actionURL?: Render, images?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.HouseAdEntry.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.weightField.id, rs.weight, undefined, cyclePath), descend(cursor, x.id, G.lifetimeCapField.id, rs.lifetimeCap, undefined, cyclePath), descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), descend(cursor, x.id, G.actionURLField.id, rs.actionURL, undefined, cyclePath), descend(cursor, x.id, G.imagesField.id, rs.images, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.weightField,G.lifetimeCapField,G.nameField,G.actionURLField,G.imagesField], cyclePath))) }
export function renderIfHouseAdImage(f: (_width: D, _height: D, _extension: D, _sha1: D, __houseAdImage: G.HouseAdImage) => Maybe<D>, rs: {width?: Render, height?: Render, extension?: Render, sha1?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.HouseAdImage.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.widthField.id, rs.width, undefined, cyclePath), descend(cursor, x.id, G.heightField.id, rs.height, undefined, cyclePath), descend(cursor, x.id, G.extensionField.id, rs.extension, undefined, cyclePath), descend(cursor, x.id, G.sha1Field.id, rs.sha1, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.widthField,G.heightField,G.extensionField,G.sha1Field], cyclePath))) }
export function renderIfIf(f: (_condition: D, _trueStatements: D, _falseStatements: D, __if: G.If) => Maybe<D>, rs: {condition?: Render, trueStatements?: Render, falseStatements?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.If.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.conditionField.id, rs.condition, undefined, cyclePath), descend(cursor, x.id, G.trueStatementsField.id, rs.trueStatements, undefined, cyclePath), descend(cursor, x.id, G.falseStatementsField.id, rs.falseStatements, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.conditionField,G.trueStatementsField,G.falseStatementsField], cyclePath))) }
export function renderIfJavaScriptProgram(f: (_statements: D, __javascriptProgram: G.JavaScriptProgram) => Maybe<D>, rs: {statements?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.JavaScriptProgram.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.statementsField.id, rs.statements, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.statementsField], cyclePath))) }
export function renderIfJSONArray(f: (_jsonArray: D, __jsonArray: G.JSONArray) => Maybe<D>, rs: {jsonArray?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.JSONArray.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.jsonArrayField.id, rs.jsonArray, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.jsonArrayField], cyclePath))) }
export function renderIfJSONNumber(f: (_jsonNumber: D, __jsonNumber: G.JSONNumber) => Maybe<D>, rs: {jsonNumber?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.JSONNumber.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.jsonNumberField.id, rs.jsonNumber, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.jsonNumberField], cyclePath))) }
export function renderIfJSONObject(f: (_keyValuePairs: D, __jsonObject: G.JSONObject) => Maybe<D>, rs: {keyValuePairs?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.JSONObject.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.keyValuePairsField.id, rs.keyValuePairs, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.keyValuePairsField], cyclePath))) }
export function renderIfJSONString(f: (_jsonString: D, __jsonString: G.JSONString) => Maybe<D>, rs: {jsonString?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.JSONString.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.jsonStringField.id, rs.jsonString, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.jsonStringField], cyclePath))) }
export function renderIfKeyValue(f: (_objectKey: D, _objectValue: D, __keyValue: G.KeyValue) => Maybe<D>, rs: {objectKey?: Render, objectValue?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.KeyValue.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.objectKeyField.id, rs.objectKey, undefined, cyclePath), descend(cursor, x.id, G.objectValueField.id, rs.objectValue, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.objectKeyField,G.objectValueField], cyclePath))) }
export function renderIfKeyValuePair(f: (_key: D, _value: D, __keyValuePair: G.KeyValuePair) => Maybe<D>, rs: {key?: Render, value?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.KeyValuePair.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.keyField.id, rs.key, undefined, cyclePath), descend(cursor, x.id, G.valueField.id, rs.value, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.keyField,G.valueField], cyclePath))) }
export function renderIfLabel(f: (_field: D, _child: D, __label: G.Label) => Maybe<D>, rs: {field?: Render, child?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Label.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.fieldField.id, rs.field, undefined, cyclePath), descend(cursor, x.id, G.childField.id, rs.child, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.fieldField,G.childField], cyclePath))) }
export function renderIfLessThan(f: (__lessThan: G.LessThan) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.LessThan.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfLessThanOrEqualTo(f: (__lessThanOrEqualTo: G.LessThanOrEqualTo) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.LessThanOrEqualTo.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfLet(f: (__let: G.Let) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Let.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfLine(f: (_children: D, __line: G.Line) => Maybe<D>, rs: {children?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Line.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.childrenField.id, rs.children, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.childrenField], cyclePath))) }
export function renderIfListType(f: (_type: D, __listType: G.ListType) => Maybe<D>, rs: {type?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.ListType.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.typeField.id, rs.type, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.typeField], cyclePath))) }
export function renderIfLoadJSON(f: (_url: D, __loadJSON: G.LoadJSON) => Maybe<D>, rs: {url?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.LoadJSON.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.urlField.id, rs.url, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.urlField], cyclePath))) }
export function renderIfModule(f: (_ctorOrAlgebraicTypes: D, _data: D, _renderCtors: D, _transformations: D, __module: G.Module) => Maybe<D>, rs: {ctorOrAlgebraicTypes?: Render, data?: Render, renderCtors?: Render, transformations?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Module.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.ctorOrAlgebraicTypesField.id, rs.ctorOrAlgebraicTypes, undefined, cyclePath), descend(cursor, x.id, G.dataField.id, rs.data, undefined, cyclePath), descend(cursor, x.id, G.renderCtorsField.id, rs.renderCtors, undefined, cyclePath), descend(cursor, x.id, G.transformationsField.id, rs.transformations, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.ctorOrAlgebraicTypesField,G.dataField,G.renderCtorsField,G.transformationsField], cyclePath))) }
export function renderIfNetworkEntry(f: (_weight: D, _lifetimeCap: D, _name: D, __networkEntry: G.NetworkEntry) => Maybe<D>, rs: {weight?: Render, lifetimeCap?: Render, name?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.NetworkEntry.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.weightField.id, rs.weight, undefined, cyclePath), descend(cursor, x.id, G.lifetimeCapField.id, rs.lifetimeCap, undefined, cyclePath), descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.weightField,G.lifetimeCapField,G.nameField], cyclePath))) }
export function renderIfNew(f: (_expression: D, _arguments: D, __new: G.New) => Maybe<D>, rs: {expression?: Render, arguments?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.New.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.expressionField.id, rs.expression, undefined, cyclePath), descend(cursor, x.id, G.argumentsField.id, rs.arguments, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.expressionField,G.argumentsField], cyclePath))) }
export function renderIfNotEquals(f: (__notEquals: G.NotEquals) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.NotEquals.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfNull(f: (__null: G.Null) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Null.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfObjectLiteral(f: (_keyValues: D, __objectLiteral: G.ObjectLiteral) => Maybe<D>, rs: {keyValues?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.ObjectLiteral.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.keyValuesField.id, rs.keyValues, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.keyValuesField], cyclePath))) }
export function renderIfOr(f: (__or: G.Or) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Or.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfParameter(f: (_name: D, __parameter: G.Parameter) => Maybe<D>, rs: {name?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Parameter.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField], cyclePath))) }
export function renderIfPlatform(f: (_name: D, __platform: G.Platform) => Maybe<D>, rs: {name?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Platform.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField], cyclePath))) }
export function renderIfProduct(f: (__product: G.Product) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Product.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfQuotient(f: (__quotient: G.Quotient) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Quotient.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfRenderCtor(f: (_forCtor: D, _d: D, __renderCtor: G.RenderCtor) => Maybe<D>, rs: {forCtor?: Render, d?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.RenderCtor.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.forCtorField.id, rs.forCtor, undefined, cyclePath), descend(cursor, x.id, G.dField.id, rs.d, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.forCtorField,G.dField], cyclePath))) }
export function renderIfRenderList(f: (_opening: D, _closing: D, _separator: D, _contextRender: D, __renderList: G.RenderList) => Maybe<D>, rs: {opening?: Render, closing?: Render, separator?: Render, contextRender?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.RenderList.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.openingField.id, rs.opening, undefined, cyclePath), descend(cursor, x.id, G.closingField.id, rs.closing, undefined, cyclePath), descend(cursor, x.id, G.separatorField.id, rs.separator, undefined, cyclePath), descend(cursor, x.id, G.contextRenderField.id, rs.contextRender, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.openingField,G.closingField,G.separatorField,G.contextRenderField], cyclePath))) }
export function renderIfRenderNameShallow(f: (_forCtor: D, __renderNameShallow: G.RenderNameShallow) => Maybe<D>, rs: {forCtor?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.RenderNameShallow.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.forCtorField.id, rs.forCtor, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.forCtorField], cyclePath))) }
export function renderIfReturn(f: (_expression: D, __return: G.Return) => Maybe<D>, rs: {expression?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Return.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.expressionField.id, rs.expression, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.expressionField], cyclePath))) }
export function renderIfStrictEquals(f: (__strictEquals: G.StrictEquals) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.StrictEquals.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfStrictNotEquals(f: (__strictNotEquals: G.StrictNotEquals) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.StrictNotEquals.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfSum(f: (__sum: G.Sum) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Sum.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfUndefined(f: (__undefined: G.Undefined) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Undefined.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfVar(f: (__var: G.Var) => Maybe<D>, rs: {} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.Var.fromID(id)), x => mapMaybe(f(x), d => renderOtherFields(cursor, sourceID, d, [], cyclePath))) }
export function renderIfVariableDeclaration(f: (_name: D, _constLetVar: D, _expression: D, __variableDeclaration: G.VariableDeclaration) => Maybe<D>, rs: {name?: Render, constLetVar?: Render, expression?: Render} = {}): Render { return (cursor, sourceID, _edgeContext, cyclePath) => bindMaybe(bindMaybe(sourceID, ({id}) => G.VariableDeclaration.fromID(id)), x => mapMaybe(f(descend(cursor, x.id, G.nameField.id, rs.name, undefined, cyclePath), descend(cursor, x.id, G.constLetVarField.id, rs.constLetVar, undefined, cyclePath), descend(cursor, x.id, G.expressionField.id, rs.expression, undefined, cyclePath), x), d => renderOtherFields(cursor, sourceID, d, [G.nameField,G.constLetVarField,G.expressionField], cyclePath))) }
