[package]
name = "progred"
version = "0.1.0"
edition = "2024"

[dependencies]
grap = { path = "../grap" }
progred-libraries = { path = "../libraries" }
progred-display = { path = "../display" }
gid = { path = "../gid" }
im = "15"
measured = { path = "../ui/measured" }
puri = { path = "../ui/puri" }
puri-vello = { path = "../ui/puri-vello" }
vello = "0.9.0"
parley = "0.9.0"
winit = "0.30.13"
pollster = "0.4.0"
ui-events = "0.3"
ui-events-winit = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.15"
clipboard-rs = "0.3.3"

[target.'cfg(target_os = "macos")'.dependencies]
muda = { version = "0.15", default-features = false }

[dev-dependencies]
skrifa = "0.42.1"
