[package]
name = "progred"
version = "0.1.0"
edition = "2024"

[dependencies]
grap = { path = "../grap" }
grap-error = { path = "../grap-error" }
grap-f64 = { path = "../grap-f64" }
grap-geometry = { path = "../grap-geometry" }
progred_graph = { path = "../progred_graph" }
progred-isa = { path = "../progred-isa" }
progred-name = { path = "../progred-name" }
progred-text = { path = "../progred-text" }
im = "15"
puri = { path = "../puri" }
puri-vello = { path = "../puri-vello" }
vello = "0.9.0"
parley = "0.9.0"
winit = "0.30.13"
pollster = "0.4.0"
ui-events = "0.3"
ui-events-winit = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.15"
clipboard-rs = "0.3.3"
muda = "0.15"
wasmtime = { version = "47.0.2", default-features = false, features = ["cranelift", "runtime", "wat", "std", "parallel-compilation"] }

[dev-dependencies]
skrifa = "0.42.1"
