[package]
name = "progred-libraries"
version = "0.1.0"
edition = "2024"

[dependencies]
gid.workspace = true
grap-runtime = { package = "grap", path = "../grap" }
progred-display.workspace = true
puri.workspace = true
puri-widgets.workspace = true
fidget-engine = { package = "fidget", version = "=0.5.0", default-features = false, features = ["raster"] }
nalgebra = "0.35"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fidget-engine = { package = "fidget", version = "=0.5.0", default-features = false, features = ["wgpu"] }
pollster.workspace = true
