[workspace]
resolver = "3"
members = [
    "graph",
    "conventions/isa",
    "conventions/name",
    "conventions/text",
    "grap",
    "grap/libraries/error",
    "grap/libraries/f64",
    "grap/libraries/geometry",
    "experiments/rust-wasm-projection",
    "progred",
    "ui/puri",
    "ui/puri-vello",
]
