[workspace]
resolver = "3"
members = [
    "graph/progred-graph",
    "graph/conventions/progred-isa",
    "graph/conventions/progred-name",
    "graph/conventions/progred-text",
    "grap",
    "grap/libraries/grap-error",
    "grap/libraries/grap-f64",
    "grap/libraries/grap-geometry",
    "experiments/rust-wasm-projection",
    "progred",
    "ui/puri",
    "ui/puri-vello",
]
